// export const icons = {
//   changeCircle: null,
//   trash: null,
//   delete: null,
//   deleteForever: null,
//   edit: null,
//   plus: null,
//   video: null,
//   arrowUp: null,
//   arrowDown: null,
//   arrowUpOutBoldOutline: null,
//   arrowDownBoldOutline: null,
//   copy: null,
//   paste: null,
//   arrowLeft: null,
//   arrowRight: null,
//   arrowLeftBold: null,
//   arrowRightBold: null,
//   swapVertical: null,
//   info: null,
//   check: null,
//   checkBoxOutline: null,
//   chevronDown: null,
//   chevronUp: null,
//   chevron_left_right: null,
//   arrow_collapse_vertical: null,
//   arrow_expand_vertical: null,
//   chevron_left: null,
//   chevron_right: null,
//   calendar: null,
//   save: null,
//   close: null,
//   cancel: null,
//   menu: null,
//   settingsCog: null,
//   logout: null,
// }

export const icons = {
  changeCircle: "sync-circle",
  trash: "delete",
  delete: "delete",
  deleteForever: "delete-forever",
  edit: "square-edit-outline",
  plus: "plus-circle",
  video: "video",
  arrowUp: "arrow-expand-up",
  arrowDown: "arrow-expand-down",
  arrowUpOutBoldOutline: "arrow-up-bold-outline",
  arrowDownBoldOutline: "arrow-down-bold-outline",
  copy: "content-copy",
  paste: "content-paste",
  arrowLeft: "arrow-left",
  arrowRight: "arrow-right",
  arrowLeftBold: "arrow-left-bold",
  arrowRightBold: "arrow-right-bold",
  swapVertical: "swap-vertical-bold",
  info: "information",
  check: "check",
  checkBoxOutline: "checkbox-blank-outline",
  chevronDown: "chevron-down",
  chevronUp: "chevron-up",
  chevron_left_right: "unfold-more-horizontal",
  arrow_collapse_vertical: "arrow-collapse-vertical",
  arrow_expand_vertical: "arrow-expand-vertical",
  chevron_left: "chevron-left",
  chevron_right: "chevron-right",
  calendar: "calendar-today",
  save: "content-save",
  close: "close",
  cancel: "cancel",
  menu: "menu",
  settingsCog: "cog-outline",
  logout: "logout",
}
