export * from "./_play-screen/welcome-screen/welcome-screen"
export * from "./_play-screen/demo-screen/demo-screen"
export * from "./_play-screen/_play-screen"

export * from "./auth-screens/signin-screen/signin-screen"
export * from "./auth-screens/registration-screen/registration-screen"
export * from "./auth-screens/welcome-screen/welcome-screen"

export * from "./trainer-screens/home-screen/home-screen.tr"
// Данчо маже
export * from "./admin-screens/exerciseDatabase-screen/exerciseDatabase-screen"
export * from "./admin-screens/other-screen/other-screen"
export * from "./admin-screens/clients2-screen/admin_clients2-screen"
export * from "./admin-screens/programs-management-screen/programs-management-screen"
export * from "./trainer-screens/training-programs-screen/training-programs-screen.tr"
export * from "./trainer-screens/edit-program-screen/edit-program-screen.tr"
export * from "./trainer-screens/train-clients-screen/train-clients-screen.tr"
export * from "./client2-screens"
export * from "./trainer-screens/mark-sessions-screen/MarkSessionsScreen"
export * from "./admin-screens/CardTypes/CardTypesScreen"
export * from "./admin-screens/ManageCardsScreen/ManageCardsScreen"
export * from "./trainer-screens/measure-clients-screen"
export * from "./trainer-screens/choose-program-screen/choose-program"

export * from "./admin-screens/home-screen/home-screen.ad"
export * from "./admin-screens/menu-screens/trainers-list-screen"
export * from "./admin-screens/menu-screens/clients-list-screen"
export * from "./admin-screens/payments-screen/payments-screen.tr"
export * from "./admin-screens/report-screen/report-screen"
export * from "./admin-screens/menu-screens/referral-screen"
export * from "./admin-screens/menu-screens/gymhalls-screen"
export * from "./admin-screens/menu-screens/card-types-list-screen"
export * from "./admin-screens/menu-screens/purchased-cards-list"

export * from "./admin-screens/menu-screens/purchased-cards-list/add-card-screen"
